name: uni_eats
description: "Uni Eats - Sistema de Delivery SaaS Regionalizado com Split de Pagamentos"
publish_to: 'none' # Impede a publicação acidental no pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Biblioteca de Ícones Adicionais do Cupertino (Padrão iOS)
  cupertino_icons: ^1.0.5

  # Serviços Essenciais do Firebase Core e Auth
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0

  # Banco de Dados NoSQL Reativo em Tempo Real
  cloud_firestore: ^4.8.0

  # Comunicação HTTP e Integração de APIs de Gateway (ex: Mercado Pago)
  http: ^1.1.0

  # Integração e Renderização de Mapas e Rotas GPS no Aplicativo
  google_maps_flutter: ^2.4.0

  # Reprodução de Vídeos em Alta Fidelidade (Reels Gastronômicos)
  video_player: ^2.7.2

  # Gerenciamento de Estado Reativo Simples e Fluido
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter para garantir as boas práticas de desenvolvimento recomendadas pelo time de engenharia
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

#  assets:
#    - assets/images/
#    - assets/images/logo.png
#    - assets/images/placeholder_mapa.png
#
#  fonts:
#    - family: SpaceGrotesk
#      fonts:
#        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
#        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
#          weight: 700
#    - family: Inter
#      fonts:
#        - asset: assets/fonts/Inter-Regular.ttf
#        - asset: assets/fonts/Inter-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Inter-Bold.ttf
#          weight: 700
