// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// ====================================================================
/// UNI EATS - CONFIGURAÇÕES EXCLUSIVAS DE CONEXÃO COM O FIREBASE
/// ====================================================================
/// Este arquivo encapsula a classe estática que provê chaves de acesso de API
/// e credenciais para sincronização segura com o Firebase de Produção/Testes.
///
/// Como Arquiteto de Software, recomendo que as chaves abaixo sejam substituídas
/// pelas chaves reais geradas no Console do Firebase (https://console.firebase.google.com)
/// ao rodar o comando: `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions não foi configurado para a plataforma Web neste projeto.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions não é compatível com a plataforma atual.',
        );
    }
  }

  /// Credenciais para Integração com a plataforma Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'SUA_API_KEY_ANDROID_AQUI_CHAVE_PRIVADA',
    appId: '1:123456789012:android:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'unieats-production-id',
    storageBucket: 'unieats-production-id.appspot.com',
  );

  /// Credenciais para Integração com a plataforma iOS (Apple)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'SUA_API_KEY_IOS_AQUI_CHAVE_PRIVADA',
    appId: '1:123456789012:ios:fedcba0987654321',
    messagingSenderId: '123456789012',
    projectId: 'unieats-production-id',
    iosBundleId: 'com.unieats.app.ios',
    storageBucket: 'unieats-production-id.appspot.com',
  );
}
